export const defaultUrl = "https://api.spoonacular.com/recipes/";
export const apiKey = "54026e881a4b4f29a732a290a1e2d6b8";
export const apikey2 = "c49be28794d74f8a840677ce108832c5";

export const TYPES = {
  SET_LOADING: "SET_LOADING",
  GET_RECIPES: "GET_RECIPES",
  GET_RECIPE_SELECT: "GET_RECIPE_SELECT",
  GET_RECIPES_SEARCH: "GET_RECIPES_SEARCH",
  ADD_TO_MENU: "ADD_TO_MENU",
  REMOVE_ONE_FROM_MENU: "REMOVE_ONE_FROM_MENU",
  CLEAR_MENU: "CLEAR_MENU",
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  GET_TOKKEN: "GET_TOKKEN",
};
